//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasaDate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class session
    {
        public int id { get; set; }
        public int id_visitors { get; set; }
        public int id_personal_computer { get; set; }
        public int id_services { get; set; }
        public int id_admin { get; set; }
        public System.DateTime date { get; set; }
        public System.TimeSpan start_time { get; set; }
        public System.TimeSpan end_time { get; set; }
    
        public virtual admin admin { get; set; }
        public virtual personal_computer personal_computer { get; set; }
        public virtual service service { get; set; }
        public virtual visitor visitor { get; set; }
    }
}
